apiVersion: v1
kind: Secret
metadata:
  name: kube-server-secret
type: Opaque # this is the type of the secret. Opaque is used for generic secrets
data:
  # this is the password of the database.
  # this is base64 encoded value of "password"
  password: cGFzc3dvcmQK
  # this is the username of the database.
  # this is base64 encoded value of "username"
  username: dXNlcm5hbWUK